---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Provision a set of public cloud instances
      local_action:
          module: rax
          name: "{{ name }}"
          flavor: "{{ flavor }}"
          image: "{{ image }}"
          count: "{{ count }}"
          key_name: "{{ keyname }}"
          region: "{{ region }}"
          wait: yes
          wait_timeout: 900
          auto_increment: no
      register: rax
      until: rax|success
      retries: 120
      delay: 60

    - name: Display rax output on failure
      debug:
        var: rax
      when:
        - rax.success|length < count

    - name: Fail on duplicate instance
      fail:
        msg: |
          While nova allows multiple instances with the same name,
          the ansible rax module will not create an instance if one
          with the requested name already exists. Please create
          instances with unique names, using the common.gen_instance_name
          function
      when:
        - rax.success|length < count
        - rax.instances|length == count

    - name: Fail if the required number of instances aren't available
      fail:
        msg: "At least one public cloud instance failed to start :("
      when: rax.success|length < count

    - name: Write inventory
      copy:
        content: |
          [job_nodes:children]
          hosts

          [hosts]
          {% for instance in rax.success %}
          {{instance.name}} ansible_host={{instance.accessIPv4}} ansible_user=root
          {% endfor %}
        dest: '{{lookup("env", "WORKSPACE")}}/rpc-gating/playbooks/inventory/hosts'

    - name: Wait for SSH to be available on all hosts
      wait_for: port=22 host="{{ item.accessIPv4 }}"
      with_items: "{{ rax.success }}"

    - name: Wait an additional amount of time for any remaning startup tasks to finish
      pause:
        minutes: 5
